version: "3.8"

services:
  web:
    container_name: web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  # web_prod:
  #   container_name: web-prod
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   ports:
      #     - "${WEB_PORT_PROD:-4000}:4000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env.production

  # Setup Databases
  # https://www.youtube.com/watch?v=qECVC6t_2mU
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_DB: ${DB_NAME:-test_db}
    ports:
      - "${DB_PORT:-5432}:5432"

  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_USER:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD:-root}
    ports:
      - "${DB_ADMIN_PORT:-5050}:80"
