version: '3'

services:
  portfolioDB:
    image: postgres:15.3
    container_name: portfolio-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=angel.szymczak
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=portfoliodev
    volumes:
      - ./postgres:/var/lib/postgresql/data

