INSERT INTO "content_project" (
  "id",
  "slug",
  "title",
  "summary",
  "description",
  "technologies",
  "outcomes",
  "technical_highlights",
  "sections",
  "demo",
  "repository",
  "img",
  "screenshots",
  "tags",
  "featured",
  "visible",
  "priority",
  "status",
  "featured_card"
) VALUES
  (
    7,
    'financial-core-simulator',
    'Financial Core Simulator',
    'Simulation engine for financial strategies with deterministic execution, CLI/API interfaces, and admin dashboard visualization.',
    'Financial Core Simulator (FCS) is a modular engine designed to process financial event streams and simulate portfolio behavior under different accounting models.',
    '["Ruby","Roda","Ruby on Rails","Avo","PostgreSQL","Dry-rb","RSpec","Mutant"]'::jsonb,
    null,
    null,
    null,
    null,
    null,
    '/images/projects/fcs/landing.png',
    '["/images/projects/fcs/landing.png"]'::jsonb,
    'Fintech • Simulation Engine • Domain-Driven Design',
    true,
    true,
    90,
    'shipped',
    '{"ribbon":{"text":"Shipped","variant":"shipped"}}'::jsonb
  ),
  (
    1,
    'crypto-screener',
    'Crypto Screener Application',
    'A feature-rich Crypto Screener App using React, Tailwind CSS, Context API and React Router.',
    'Comprehensive cryptocurrency screening app with real-time market data and advanced filtering capabilities.',
    '["React","Tailwind CSS","Context API","React Router","JavaScript"]'::jsonb,
    'Achieved faster load times through optimized data fetching and caching.',
    '["Real-time data stream","Client-side cache strategy"]'::jsonb,
    null,
    'https://crypto-screener-demo.com',
    'https://github.com/angelpixel-core/crypto-screener',
    '/images/projects/crypto-screener-cover-image.jpg',
    '["/images/projects/crypto-screener-cover-image.jpg"]'::jsonb,
    'Realtime Market Analytics • BackOffice • React • Tailwind • Context API',
    true,
    false,
    60,
    'in-progress',
    '{"ribbon":{"text":"Incoming","variant":"wip"}}'::jsonb
  )
ON CONFLICT ("id") DO UPDATE SET
  "slug" = EXCLUDED."slug",
  "title" = EXCLUDED."title",
  "summary" = EXCLUDED."summary",
  "description" = EXCLUDED."description",
  "technologies" = EXCLUDED."technologies",
  "outcomes" = EXCLUDED."outcomes",
  "technical_highlights" = EXCLUDED."technical_highlights",
  "sections" = EXCLUDED."sections",
  "demo" = EXCLUDED."demo",
  "repository" = EXCLUDED."repository",
  "img" = EXCLUDED."img",
  "screenshots" = EXCLUDED."screenshots",
  "tags" = EXCLUDED."tags",
  "featured" = EXCLUDED."featured",
  "visible" = EXCLUDED."visible",
  "priority" = EXCLUDED."priority",
  "status" = EXCLUDED."status",
  "featured_card" = EXCLUDED."featured_card",
  "updated_at" = now();
