INSERT INTO "content_article" (
  "id",
  "title",
  "url",
  "slug",
  "lang",
  "reading_time",
  "published_at",
  "summary",
  "content",
  "img",
  "img_alt",
  "featured",
  "visible",
  "priority",
  "category",
  "badges",
  "status"
) VALUES
  (
    14,
    'Los datos financieros no mienten... hasta que los procesas mal',
    '/articles/datos-financieros-no-mienten',
    'datos-financieros-no-mienten',
    'ES',
    12,
    '2026-03-27',
    'Como errores en el procesamiento de datos financieros pueden costar millones, y como disenar sistemas deterministas evita resultados incorrectos.',
    null,
    '/images/articles/fcs-overview.svg',
    'Financial systems data quality overview',
    true,
    true,
    90,
    'Architecture',
    '["Fintech","Deterministic Processing"]'::jsonb,
    'published'
  ),
  (
    15,
    'Building resilient event pipelines',
    '/articles/building-resilient-event-pipelines',
    'building-resilient-event-pipelines',
    'EN',
    8,
    '2026-03-10',
    'Patterns for designing resilient, observable, and replayable event-driven systems.',
    null,
    '/images/articles/event-pipeline.svg',
    'Event pipeline architecture diagram',
    false,
    true,
    80,
    'Architecture',
    '["Event-Driven","Observability"]'::jsonb,
    'published'
  )
ON CONFLICT ("id") DO UPDATE SET
  "title" = EXCLUDED."title",
  "url" = EXCLUDED."url",
  "slug" = EXCLUDED."slug",
  "lang" = EXCLUDED."lang",
  "reading_time" = EXCLUDED."reading_time",
  "published_at" = EXCLUDED."published_at",
  "summary" = EXCLUDED."summary",
  "content" = EXCLUDED."content",
  "img" = EXCLUDED."img",
  "img_alt" = EXCLUDED."img_alt",
  "featured" = EXCLUDED."featured",
  "visible" = EXCLUDED."visible",
  "priority" = EXCLUDED."priority",
  "category" = EXCLUDED."category",
  "badges" = EXCLUDED."badges",
  "status" = EXCLUDED."status",
  "updated_at" = now();
