const contactPointsMock = [
  {
    id: 1,
    type: "communication",
    provider: "email",
    label: "Email",
    href: "mailto:contact@site.com",
    value: "mailto:contact@site.com",
    icon: "Mail",
  },
  {
    id: 2,
    type: "social",
    provider: "linkedin",
    label: "LinkedIn",
    href: "https://linkedin.com/in/user",
    value: "https://linkedin.com/in/user",
    icon: "LinkedIn",
    // styles: "text-blue-600",
  },
  {
    id: 3,
    type: "social",
    provider: "github",
    label: "GitHub",
    href: "https://github.com/user",
    value: "https://github.com/user",
    icon: "GitHub",
    // styles: "text-black dark:text-white",
  },
  {
    id: 4,
    type: "communication",
    provider: "whatsapp",
    label: "WhatsApp",
    href: "https://wa.me/5491122334455",
    value: "https://wa.me/5491122334455",
    icon: "WhatsApp",
  },
  {
    id: 5,
    type: "social",
    provider: "twitter",
    label: "Twitter",
    href: "https://twitter.com/username",
    value: "https://twitter.com/username",
    icon: "Twitter",
    // styles: "text-sky-500",
  },
  {
    id: 6,
    type: "social",
    provider: "dribbble",
    label: "Dribbble",
    href: "https://dribbble.com/username",
    value: "https://dribbble.com/username",
    icon: "Dribbble",
    // styles: "text-pink-500",
  },

  {
    id: 7,
    type: "messaging",
    provider: "telegram",
    label: "Telegram",
    href: "https://t.me/articangel",
    value: "https://t.me/articangel",
    icon: "Telegram",
  },
];

export default contactPointsMock;
