export { default as Content } from "./Content";
export { default as Profile } from "./Profile";
export { default as Customer } from "./Customer";
// export { Academic } from "./Academic";
export { default as Feature } from "./Feature";
// export { JobExperience } from "./JobExperience";
// export { Article } from "./Article";
// export { Project } from "./Project";
// export { Technology } from "./Technology";
// export { JobExtraInfo } from "./JobExtraInfo";
export { default as Social } from "./Social";
